[package]
  name = "mike_os"
  version = "0.1.0"
  authors = ["Michael Westbom <michael@agilion.com>"]

[lib]
  crate-type = ["staticlib"]

[dependencies]
  spin = "0.3.4"
[dependencies.multiboot2]
  git = "https://github.com/phil-opp/multiboot2-elf64"
